# Generated by Django 5.1.4 on 2025-01-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Телеграм чат-id"
            ),
        ),
    ]
