# Generated by Django 5.1.4 on 2025-01-08 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Введите место для привычки",
                        max_length=255,
                        verbose_name="Место привычки",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        help_text="Введите время в формате (01.01.2001 12:30)",
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Введите действие привычки",
                        max_length=510,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "SignPleasantHabit",
                    models.BooleanField(verbose_name="Признак приятной привычки"),
                ),
                (
                    "Periodicity",
                    models.PositiveIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                        ],
                        default=1,
                        help_text="Выберите период привычки в днях.",
                        verbose_name="Периодичность привычки. в днях",
                    ),
                ),
                (
                    "Reward",
                    models.CharField(
                        help_text="Вознаграждение",
                        max_length=255,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "TimeToComplete",
                    models.PositiveIntegerField(
                        help_text="Введите время выполнения привычки (не больше 120сек)",
                        verbose_name="Время на выполнение (не больше 120сек)",
                    ),
                ),
                (
                    "SignPublic",
                    models.BooleanField(verbose_name="Признак публичной привычки"),
                ),
                (
                    "RelatedHabit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit_tracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
