# Generated by Django 5.1.4 on 2025-01-08 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0002_alter_habit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="RelatedHabit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habit_tracker.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="Reward",
            field=models.CharField(
                blank=True,
                help_text="Вознаграждение",
                max_length=255,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
