# Generated by Django 5.1.4 on 2025-01-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0003_alter_habit_relatedhabit_alter_habit_reward"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="Periodicity",
            new_name="periodicity",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="RelatedHabit",
            new_name="related_habit",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="Reward",
            new_name="reward",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="SignPleasantHabit",
            new_name="sign_pleasant_habit",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="SignPublic",
            new_name="sign_public",
        ),
        migrations.RenameField(
            model_name="habit",
            old_name="TimeToComplete",
            new_name="time_to_complete",
        ),
    ]
