# Generated by Django 5.1.4 on 2025-01-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0004_rename_periodicity_habit_periodicity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                help_text="Введите время в формате (12:30)",
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
