# Generated by Django 5.1.4 on 2025-01-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0005_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7)],
                default=1,
                help_text="Выберите период привычки в днях.",
                verbose_name="Периодичность привычки. в днях",
            ),
        ),
    ]
